name: "Build Staging"
on:
  push:
    branches:
      - develop
jobs:
  build_qa:
    name: Build QA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Push Branch Develop - Build Staging"